= Workshop Prerequisites

== All Sections

- http://git-scm.com/downloads[Git] ("brew install git")
- A https://github.com[GitHub] account
- Your favorite Java editor (Eclipse, IntelliJ IDEA, Netbeans)
- https://github.com/cloudfoundry/cli/releases[The Cloud Foundry CLI] - download the latest!

Needless to say you'll need a laptop! For best experience, a Mac or Linux environment is ideal.

== Morning Session

The morning session of the workshop will require a free account on Pivotal Web Services.
You can create a 60-day trial with no credit card at https://run.pivotal.io.

== Afternoon Session

The afternoon session of the workshop will require the use of a FREE Cloudbees account.
Create one at https://grandcentral.cloudbees.com.
Once you're set up, click on "Get Started with Builds" to provision your Jenkins instance.
We'll complete the remainder of the setup during the lab, but it's important to get the Jenkins instance provisioned in advance so that you don't lose 10 minutes of workshop time!

It will also require the use of a FREE TRIAL account of Artifactory Online from JFrog.
You can obtain an account at https://www.jfrog.com/registration/registration.html].
This one is a bit quicker, but you still should try to create it before the workshop.
