= CF Community Workshop Kit
Matt Stine <mstine@gopivotal.com>

This is a WIP attempt to package the Cloud Foundry Deep Dive workshop that I delivered at UberConf 2014 into a reusable form for local CF community events hosted by CF Platform Engineers and other Pivotal staff.

== Workshop Flow

The workshop was originally delivered on the last day of the UberConf show. That day is broken into four 90-minute sessions, with two 15-minute coffee breaks and a lunch break of 1 hour 15 minutes. The sessions are as follows:

. *The Developer Experience*
+
This workshop introduces the business ``why'' of Cloud Foundry with a nod to Microservices architectures.
It then takes the developer through a hands-on ``day in the life'' experience of interacting with Pivotal Web Services:
+
Target My Cloud Foundry Provider:: walkthrough of PWS registration, download CF CLI, target/login.
Push My App:: push the Spring Music application, high-level talk through of app push/stage/deploy.
Bind My App to Backing Services:: bind Spring Music to an ElephantSQL PostgreSQL database, high-level talk through of service creation/binding, explain +VCAP_SERVICES+, point to Spring Cloud.
Scale My App:: push cf-scale-boot application, scale up, scale down, high-level talk through of dynamic routing.
Monitor My App’s Logs:: tail cf-scale-boot logs, high-level discussion of loggregator.
Monitor My App’s Health:: hit the ``kill switch'' in cf-scale-boot, watch the events in the logs, show +cf events+, watch the app restart, high-level talk through of health manager.
Monitor My App’s Performance:: bind to New Relic service, re-push application, high-level discussion of NR agent fetching via BP, poke around in NR interface.

. *Architecture and Operations*
+
The primary goals of this session are to:
+
* Get bosh-lite deployed for the student. This makes ``deploying your own CF'' real for them, and also gives them an admin environment for later labs.
* While BOSH and CF are deploying, do a deep dive into the CF architecture via animated slides illustrating push, stage, deploy, scale, and health management.
* Also do a brief dive into BOSH, including why BOSH, what it is, and animations of how it works.
It's not an operations focused workshop, so we keep the treatment light.
* Quickly prove that I can push an app to my own CF in the same exact way I can push an app to PWS.

. *Enabling Continuous Delivery*
+
The primary goals of this session are to:
+
* Give a brief, platform-agnostic overview of the ``why'' and ``what'' of Continuous Delivery.
The purpose is to simply educate the student and bring everyone to the same level.
* Explain how Cloud Foundry benefits Continuous Delivery.
* Provide a hands-on lab experience where the student takes a Spring Boot microservice application and builds a continuous delivery pipeline for it using Jenkins, Artifactory, and Cloud Foundry. This is all done using free trial SaaS versions of the software.

. *Custom Buildpacks and Data Services*
+
The primary goals of this session are to:
+
* Give an overview of the extension points available to Cloud Foundry users.
* Provide a buildpack overview with a deep focus on the Java buildpack (my target audience has been Java conferences)
* Provide an overview of service options, from user-provided to managed services, including an overview of the V2 Service Broker API.
* Provide two hands-on lab experiences:
** _Java Buildpack Extension_
*** via customization (add a new framework component)
*** via configuration (upgrade to Java 8)
** _Service Broker Development/Management_
*** deploy a service broker for ``HashMap as a Service (HaaSh).'' Register the broker, make the plan public.
*** create an instance of the HaaSh service
*** deploy a client app, bind to the service, and test it


== Contents

So far this consists of:

* this README
* a link:prerequisites.adoc[prerequisites] doc
* the link:slides[slides] (in Keynote format)

It also references the following additional GitHub repositories (most of which are housed under the cf-platform-eng organization, but there are a few exceptions):

* https://github.com/cloudfoundry-samples/spring-music[Spring Music Sample Application]
* https://github.com/cf-platform-eng/cf-scale-boot[CF Scale Boot Sample Application]
* https://github.com/cf-platform-eng/bosh-lite-installer[BOSH Lite Environment Validator and Installer Scripts]
* https://github.com/cf-platform-eng/cf-workshop-cd-module[Continuous Delivery Hands-On Lab]
* https://github.com/mstine/citytest[Current Sample App for CD Lab]
* https://github.com/cf-platform-eng/cf-workshop-bp-module[Buildpacks Hands-On Lab]
* https://github.com/cf-platform-eng/cf-workshop-sb-module[Service Brokers Hands-On Lab]
* https://github.com/mstine/haash-broker[haash-broker: Sample Service Broker App]
* https://github.com/mstine/haash-client[haash-client: Sample Client for haash-broker]


== TODO's

* Ensure that no special fonts appear in Keynote decks. If they do, vectorize into images.
* Determine license for the content. I would like to use http://creativecommons.org/licenses/by-sa/4.0/[CC BY-SA 4.0], but some of the slides in the decks are derivatives of slides from decks carrying the Pivotal copyright.
* Find a more ``proper'' example app repo to use for the continuous delivery lab. Probably https://github.com/cf-platform-eng/spring-boot-cities[this], but will require a couple of small modifications.
* Remove ``UberConf'' specific references throughout content.
* Put some tests (e.g. https://code.google.com/p/rest-assured) in place for haash-broker.
* Add a ``smoke test'' and ``promotion'' step to the continuous delivery lab.
