= Pivotal Cloud Platform Roadshow Workshop Kit
Matt Stine <mstine@pivotal.io>

Workshop kit containing content for the Pivotal Cloud Platform Roadshow (http://www.pivotal.io/cloud-platform-roadshow/).

== Workshop Flow

The workshop was originally delivered on the last day of the UberConf show. That day is broken into four 90-minute sessions, with two 15-minute coffee breaks and a lunch break of 1 hour 15 minutes.

The schedule has been altered to fit the PCP Roadshow format, with 75-minute sessions. It also accomodates two keynotes:

8:30 - 9:00 AM:: Registration/Breakfast/Coffee
9:00 - 10:00 AM:: Morning Keynote (_3rd Platform_)
10:00 - 10:15 AM:: Coffee Break
10:15 - 11:30 AM:: Session #1 - The Developer Experience
11:30 - 11:45 AM:: Coffee Break
11:45 - 1:00 PM:: Session #2 - Architecture and Operations
1:00 - 2:30 PM:: Lunch and Keynote (_Architecting for Continuous Delivery_)
2:30 - 2:45 PM:: Coffee Break
2:45 - 4:00 PM:: Session #3 - Custom Buildpacks and Data Services
4:00 - 4:15 PM:: Coffee Break
4:15 - 5:30 PM:: Session #4 - Enabling Continuous Delivery

The sessions are as follows:

. *The Developer Experience*
+
This workshop introduces the business ``why'' of Cloud Foundry with a nod to Microservices architectures.
It then takes the developer through a hands-on ``day in the life'' experience of interacting with Pivotal Web Services:
+
Target My Cloud Foundry Provider:: walkthrough of PWS registration, download CF CLI, target/login.
Push My App:: push the Spring Music application, high-level talk through of app push/stage/deploy.
Bind My App to Backing Services:: bind Spring Music to an ElephantSQL PostgreSQL database, high-level talk through of service creation/binding, explain +VCAP_SERVICES+, point to Spring Cloud.
Scale My App:: push cf-scale-boot application, scale up, scale down, high-level talk through of dynamic routing.
Monitor My App’s Logs:: tail cf-scale-boot logs, high-level discussion of loggregator.
Monitor My App’s Health:: hit the ``kill switch'' in cf-scale-boot, watch the events in the logs, show +cf events+, watch the app restart, high-level talk through of health manager.
Monitor My App’s Performance:: bind to New Relic service, re-push application, high-level discussion of NR agent fetching via BP, poke around in NR interface.

. *Architecture and Operations*
+
The primary goals of this session are to:
+
* Do a deep dive into the CF architecture via animated slides illustrating push, stage, deploy, scale, and health management.
* Also do a brief dive into BOSH, including why BOSH, what it is, and animations of how it works.
It's not an operations focused workshop, so we keep the treatment light.
* Discuss the value adds to CF BOSH OSS that Pivotal brings through the Pivotal Ops Manager product and our associated ecosystem of data and mobile services.
* Brief demo of Operations Manager environment (presenter's discretion)

. *Custom Buildpacks and Data Services*
+
The primary goals of this session are to:
+
* Give an overview of the extension points available to Cloud Foundry users.
* Provide a buildpack overview with a deep focus on the Java buildpack (my target audience has been Java conferences)
* Provide an overview of service options, from user-provided to managed services, including an overview of the V2 Service Broker API.
* Provide a live demo of either:
** _Service Broker Development/Management_ (*_PREFERABLE_*)
*** deploy a service broker for ``HashMap as a Service (HaaSh).'' Register the broker, make the plan public.
*** create an instance of the HaaSh service
*** deploy a client app, bind to the service, and test it
** _Java Buildpack Extension_
*** via customization (add a new framework component)
*** via configuration (upgrade to Java 8)

. *Enabling Continuous Delivery*
+
The primary goals of this session are to:
+
* Give a brief, platform-agnostic overview of the ``why'' and ``what'' of Continuous Delivery.
The purpose is to simply educate the student and bring everyone to the same level.
* Explain how Cloud Foundry benefits Continuous Delivery.
* Provide a live demo where the presenter takes a Spring Boot microservice application and builds a continuous delivery pipeline for it using Jenkins, Artifactory, and Cloud Foundry. This is done using a PCF environment and SaaS versions of Jenkins and Artifactory.

== Contents

So far this consists of:

* this README
* a link:prerequisites.adoc[prerequisites] doc
* the link:slides[slides] (in Keynote format)
* the link:demos[demos]
** link:demos/continuous-delivery-lab.adoc[Continuous Delivery Demo]
** link:demos/buildpack-lab.adoc[Buildpacks Demo]
** link:demos/service-broker-lab.adoc[Service Brokers Demo]

It also references the following additional sample app GitHub repositories (most of which are housed under the cf-platform-eng organization, but there are a few exceptions):

* https://github.com/cloudfoundry-samples/spring-music[Spring Music Sample Application]
* https://github.com/Pivotal-Field-Engineering/PCF-demo[Heat Map Sample Application]
* https://github.com/cf-platform-eng/cf-scale-boot[CF Scale Boot Sample Application]
* https://github.com/mstine/citytest[Current Sample App for CD Lab]
* https://github.com/mstine/haash-broker[haash-broker: Sample Service Broker App]
* https://github.com/mstine/haash-client[haash-client: Sample Client for haash-broker]


