= CF Workshop Service Broker Lab
Matt Stine <matt.stine@gmail.com>

== Intro

This lab will guide you through:

* deploying a Service Broker as an app to Cloud Foundry
* registering the Broker with the Cloud Controller
* making the single plan in the catalog ``public''
* creating an instance of a service
* pushing and binding a test app to that service
* testing the app's interaction with the service

The Service Broker for this lab is for a service called HashMap as a Service (HaaSh). It wraps a minimal REST API around a Java HashMap implementation, and each service creation event results in a newly allocated Map.

== Steps

. Clone the haash-broker repo:
+
[source,bash]
----
$ git clone https://github.com/mstine/haash-broker.git
$ cd haash-broker
----

. Edit the file +src/main/resources/import.sql+, find +<uniquetoken>+ and substitute something like your name (do this same substitution everywhere you see +<uniquetoken>+ throughout the instructions):
+
[source,sql]
----
insert into services (id, name, description, bindable) values ('1', 'HaaSh-<uniquetoken>', 'HaaSh - HashMap as a Service', true)
insert into plans (id, name, description, service_id) values ('1', 'basic', 'Basic Plan','1');
----

. Build the project using Gradle Wrapper:
+
[source,bash]
----
$ ./gradlew assemble
----

. Ensure that you have targeted your bosh-lite Cloud Foundry deployment, and push the app:
+
[source,bash]
----
$ cf push -m 512m -p build/libs/haash-broker-0.0.1-SNAPSHOT.jar haash-broker-<uniquetoken>
----

. Once the app is running, register the broker with the Cloud Controller (substitute the route for your broker app):
+
[source,bash]
----
$ cf create-service-broker haash-broker-<uniquetoken> warreng natedogg http://haash-broker-<uniquetoken>.s#.pcf.pivotal.io
----

. Next, we need to make the service plan public, as all plans start private by default.
+
[source,bash]
----
$ cf enable-service-access haash-<uniquetoken>
----

. You should now be able to see your service in the marketplace:
+
[source, bash]
----
$ cf marketplace
Getting services from marketplace in org default / space development as admin...
OK

service   plans   description
HaaSh-<uniquetoken>     basic   HaaSh - HashMap as a Service
----

. Next, create an instance of your service:
+
[source, bash]
----
$ cf create-service HaaSh-<uniquetoken> basic my-hash
----

. Now it's time to push and bind to the client app. First clone the haash-client repo:
+
[source,bash]
----
$ git clone https://github.com/mstine/haash-client.git
$ cd haash-client
----

. Build the project using Gradle Wrapper:
+
[source,bash]
----
$ ./gradlew assemble
----

. We'll use a CF application manifest to take care of our metadata, including binding to the HaaSh service. It's already in the project, but you can see it reproduced here:
+
[source,yaml]
----
applications:
- name: haash-client
  memory: 512M
  path: build/libs/haash-client-0.0.1-SNAPSHOT.jar
  services:
  - my-hash
----
+
This allows a simpler push experience:
+
[source,bash]
----
$ cf push -n haash-client-<uniquetoken>
----

. Once the application is running, you can test it:
+
[source,bash]
----
$ curl haash-client-<uniquetoken>.s#.pcf.pivotal.io/HaaSh/foo -d '{"value":"bar"}' -X PUT
{}

$ curl haash-client-<uniquetoken>.s#.pcf.pivotal.io/HaaSh/foo
{"value":"bar"}
----

. Congratulations! You've completed the lab. Don't forget to spend some time looking at the source code for haash-broker and compare what you see to the [Service Broker API Documentation](http://docs.cloudfoundry.org/services/api.html).
